/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
import java.util.Base64;

/**
 * @author chenyuanbo
 * @DATE: 2024/2/19
 */
public class Test {

    public static void main(String[] args) {
        String param = "eyJuYW1lIjoiMTIzXzE3MDg0NzkyMzQyODciLCJlbnYiOnsiZW5naW5lIjoic3BhcmsiLCJ0eXBlIjoiYmF0Y2gifSwic291cmNlcyI6W3sicGx1Z2luIjoiaGRmcyIsInR5cGUiOiJzb3VyY2UiLCJjb25maWciOnsicGFzc3dvcmQiOiIxMjMiLCJkYXRhYmFzZSI6ImRlZmF1bHQiLCJkcml2ZXIiOiIiLCJ1c2VyIjoiaGRmcyIsIm91dHB1dF90YWJsZSI6ImBkZWZhdWx0X2RlZmF1bHRgIiwidGFibGUiOiJkZWZhdWx0LmRlZmF1bHQiLCJ1cmwiOiJoZGZzOi8vMTkyLjE2OC4xLjIzNjo4MDIwL251bGwifX1dLCJ0cmFuc2Zvcm1zIjpbeyJwbHVnaW4iOiJzcWwiLCJ0eXBlIjoiaW52YWxpZGF0ZV9pdGVtcyIsImNvbmZpZyI6eyJpbnZhbGlkYXRlX2l0ZW1zX3RhYmxlIjoiaW52YWxpZGF0ZV9pdGVtc18wZWQ4YTQ1OCIsImluZGV4IjowLCJvdXRwdXRfdGFibGUiOiJpbnZhbGlkYXRlX2l0ZW1zXzBlZDhhNDU4Iiwic3FsIjoic2VsZWN0ICogZnJvbSBgZGVmYXVsdF9kZWZhdWx0YCB3aGVyZSAoYGlkYCBpcyBudWxsIG9yIGBpZGAgPSAnJykifX0seyJwbHVnaW4iOiJzcWwiLCJ0eXBlIjoiYWN0dWFsX3ZhbHVlIiwiY29uZmlnIjp7ImludmFsaWRhdGVfaXRlbXNfdGFibGUiOiJpbnZhbGlkYXRlX2l0ZW1zXzBlZDhhNDU4IiwiaW5kZXgiOjAsIm91dHB1dF90YWJsZSI6ImludmFsaWRhdGVfY291bnRfMGVkOGE0NTgiLCJzcWwiOiJzZWxlY3QgY291bnQoMSkgYXMgYWN0dWFsX3ZhbHVlXzBlZDhhNDU4IGZyb20gaW52YWxpZGF0ZV9pdGVtc18wZWQ4YTQ1OCJ9fV0sInNpbmtzIjpbeyJwbHVnaW4iOiJteXNxbCIsImNvbmZpZyI6eyJqb2JfZXhlY3V0aW9uX2lkIjoxMDksInVybCI6ImpkYmM6bXlzcWw6Ly8xOTIuMTY4LjEuMjAxOjMzMDcvZGF0YXZpbmVzP3VzZVVuaWNvZGU9dHJ1ZSZjaGFyYWN0ZXJFbmNvZGluZz1VVEYtOCZ1c2VTU0w9ZmFsc2Umc2VydmVyVGltZXpvbmU9QXNpYS9TaGFuZ2hhaSIsInNxbCI6InNlbGVjdCAxMDkgYXMgam9iX2V4ZWN1dGlvbl9pZCwgJ2NvbHVtbl9ibGFuaycgYXMgbWV0cmljX25hbWUsICcrR1VLS1JEWTNXNkJFWjBJVldTL1c0T0xLNFEySlo4QUlTVUZISS8yS1RVPScgYXMgdW5pcXVlX2NvZGUsIGFjdHVhbF92YWx1ZV8wZWQ4YTQ1OCBhcyBhY3R1YWxfdmFsdWUsICcyMDI0LTAyLTIxIDA5OjMzOjU3JyBhcyBkYXRhX3RpbWUsICcyMDI0LTAyLTIxIDA5OjMzOjU3JyBhcyBjcmVhdGVfdGltZSwgJzIwMjQtMDItMjEgMDk6MzM6NTcnIGFzIHVwZGF0ZV90aW1lIGZyb20gaW52YWxpZGF0ZV9jb3VudF8wZWQ4YTQ1OCIsInNyY19jb25uZWN0b3JfdHlwZSI6Im15c3FsIiwiaW52YWxpZGF0ZV9pdGVtc190YWJsZSI6ImludmFsaWRhdGVfaXRlbXNfMGVkOGE0NTgiLCJwYXNzd29yZCI6IlN6bHgxMjMkIiwiZHJpdmVyIjoiY29tLm15c3FsLmNqLmpkYmMuRHJpdmVyIiwibWV0cmljX3VuaXF1ZV9rZXkiOiIwZWQ4YTQ1OCIsImV4cGVjdGVkX3ZhbHVlIjoiMCIsInVzZXIiOiJyb290Iiwib3V0cHV0X3RhYmxlIjoiZHZfYWN0dWFsX3ZhbHVlcyIsInRhYmxlIjoiZHZfYWN0dWFsX3ZhbHVlcyJ9fSx7InBsdWdpbiI6Im15c3FsIiwiY29uZmlnIjp7ImpvYl9leGVjdXRpb25faWQiOjEwOSwidXJsIjoiamRiYzpteXNxbDovLzE5Mi4xNjguMS4yMDE6MzMwNy9kYXRhdmluZXM/dXNlVW5pY29kZT10cnVlJmNoYXJhY3RlckVuY29kaW5nPVVURi04JnVzZVNTTD1mYWxzZSZzZXJ2ZXJUaW1lem9uZT1Bc2lhL1NoYW5naGFpIiwic3FsIjoic2VsZWN0IDEwOSBhcyBqb2JfZXhlY3V0aW9uX2lkLCAnMGVkOGE0NTgnIGFzIG1ldHJpY191bmlxdWVfa2V5LCAnc2luZ2xlX3RhYmxlJyBhcyBtZXRyaWNfdHlwZSwgJ2NvbHVtbl9ibGFuaycgYXMgbWV0cmljX25hbWUsICdjb21wbGV0ZW5lc3MnIGFzIG1ldHJpY19kaW1lbnNpb24sICdkZWZhdWx0JyBhcyBkYXRhYmFzZV9uYW1lLCAnZGVmYXVsdCcgYXMgdGFibGVfbmFtZSwgJ2lkJyBhcyBjb2x1bW5fbmFtZSwgYWN0dWFsX3ZhbHVlXzBlZDhhNDU4IGFzIGFjdHVhbF92YWx1ZSwgMCBhcyBleHBlY3RlZF92YWx1ZSwgJ25vbmUnIGFzIGV4cGVjdGVkX3R5cGUsICdjb3VudCcgYXMgcmVzdWx0X2Zvcm11bGEsICdndCcgYXMgb3BlcmF0b3IsIDAuMCBhcyB0aHJlc2hvbGQsICcyMDI0LTAyLTIxIDA5OjMzOjU3JyBhcyBjcmVhdGVfdGltZSwgJzIwMjQtMDItMjEgMDk6MzM6NTcnIGFzIHVwZGF0ZV90aW1lIGZyb20gaW52YWxpZGF0ZV9jb3VudF8wZWQ4YTQ1OCAiLCJzcmNfY29ubmVjdG9yX3R5cGUiOiJteXNxbCIsImludmFsaWRhdGVfaXRlbXNfdGFibGUiOiJpbnZhbGlkYXRlX2l0ZW1zXzBlZDhhNDU4IiwicGFzc3dvcmQiOiJTemx4MTIzJCIsImRyaXZlciI6ImNvbS5teXNxbC5jai5qZGJjLkRyaXZlciIsIm1ldHJpY191bmlxdWVfa2V5IjoiMGVkOGE0NTgiLCJleHBlY3RlZF92YWx1ZSI6IjAiLCJ1c2VyIjoicm9vdCIsIm91dHB1dF90YWJsZSI6ImR2X2pvYl9leGVjdXRpb25fcmVzdWx0IiwidGFibGUiOiJkdl9qb2JfZXhlY3V0aW9uX3Jlc3VsdCJ9fV19";
        System.out.println(new String(Base64.getDecoder().decode(param)));
    }

}
